name: cesunapp
description: "Aplicación institucional CESUN con animaciones, PDFs y enlaces web."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  drop_down_list: ^2.0.0
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  url_launcher: ^6.2.5
  flutter_pdfview: ^1.3.0
  path_provider: ^2.1.2
  shared_preferences: ^2.0.1
  flutter_dotenv: ^5.1.0  
  dio: ^5.4.3
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.0
  syncfusion_flutter_pdfviewer: ^30.1.41
  permission_handler: ^12.0.1
  path: ^1.9.0
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

    - assets/jsons/
    - assets/images/
    - assets/pdfs/
